### PR TITLE
ADM: enumerate known error values

### PR DESCRIPTION
**Pull request by talklittle**
avoid crash at `String.to_existing_atom/1`

### CODE REVIEW

**Comment by hpopp** [comment]
I should probably implement similar handling in FCM to be safe. Did ADM change its error response?

**Comment by hpopp** [comment]
Also worth noting, this is technically an API breaking change, but needs to be pushed regardless.

**Comment by talklittle** [comment]
AFAIK nothing has changed with ADM's responses, just never caught the problem before. The doctest with `"InvalidRegistration"` was a typo or bad copy from FCM docs; correct was always `"InvalidRegistrationId"` as documented in https://hexdocs.pm/pigeon/adm-amazon-android.html#error-responses

The actual error I ran into in production was with `"AccessTokenExpired"` which is already also documented in Pigeon.

Easy to slip by when trying to reproduce it; with my newly added tests, the first invocation of `mix test` seemed to miss the problem, while the subsequent ones caught the error. I guess the compile step temporarily registers the atoms into the VM from the `@type` at https://github.com/codedge-llc/pigeon/blob/f849bc5ce066d9de630b1861851ea9c6b8e61bef/lib/pigeon/adm/notification.ex#L55

Yeah, I think FCM and APNS should avoid `String.to_existing_atom/1` too. It's dangerous unless you are certain the atoms are already registered in the VM.

**Comment by hpopp** [comment]
Nice, well I'll implement the FCM and APNS fixes then. I'm not sure why I didn't think to do it this way in the first place ¯\_(ツ)_/¯

**Pull request merged**
