### PR TITLE
Amazon ADM

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by hpopp** [comment]
Thank you so much for this! I've been out of town for the past several days but I'll take a closer look when I get back. At the moment pigeon is stuck at its current version on hex because of its recent policy change regarding github dependencies. When I resolve it, I'll roll this in with those changes in a `v0.10.0` release.

I'm not entirely familiar with ADM and haven't ever used it in a project. Would you mind taking responsibility for maintaining this functionality moving forward?

**Comment by talklittle** [comment]
@hpopp Cool thanks. Sure, I'll maintain the functionality, since I expect to continue using Pigeon for push notifications, as well as continuing to support Amazon Android devices. I'll let you know if that ever has to change.

**Comment by hpopp** [comment]
Everything checked out great! With luck there will be a release out on hex this weekend.

A bit of a heads up, there's going to be a change in the config style. APNS will be supporting multiple worker pools, so each APNS, GCM and ADM will each get their own config blocks.

The new ADM one will look something like:
```elixir
 config :pigeon, :adm,
  client_id: "client id here",
  client_secret: "client secret here"
```

Don't worry about unit tests. I should probably be able to update them myself.

**Comment by talklittle** [comment]
Awesome! Thanks a lot!

**Pull request merged**
