### PR TITLE
Fix Elixir 1.17 deprecation in Pigeon 1.6.x

### PR DESCRIPTION
**Pull request by nathany-copia**
#258

### CODE REVIEW

**Comment by egze** [comment]
Please merge it. cc @hpopp

**Comment by hpopp** [comment]
Thanks!

**Comment by nathany-copia** [comment]
Thank you!

**Comment by nathany-copia** [comment]
We're using this until 1.6.3 comes out -- for anyone else who needs this patch.

```
# Waiting for Pigeon 1.6.x release with Elixir 1.17 support.
{:pigeon, "~> 1.6.2", github: "codedge-llc/pigeon", ref: "6bc63f2"},
```

**Comment by hpopp** [comment]
Went ahead and published 1.6.3 🚀

**Comment by sf3ris** [comment]
@hpopp @nathany-copia Thank you very much for your work on this issue!
We are currently using the version `2.0.0` due to some nice features we have foreseen, would it be possible to add the same fixes on the master branch? 

I can open a PR on master branch with the fix if you wish 🙏

**Pull request merged**
