### PR TITLE
ADM API updates

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by hpopp** [comment]
Looks pretty good. Does ADM support multiple reg IDs in a single notification response?

**Comment by talklittle** [comment]
Amazon's API does not. Each request is per-reg-ID. Is this something you need (me) to do in Pigeon? I.e. combine the responses.

**Comment by hpopp** [comment]
I'm still trying to reason out the final API for all three services, but here's it's behavior so far:

**APNS**
```elixir
# one push, one token
n = APNS.Notification.new("msg", "token", "topic")
{:ok, notif} = APNS.push(n)
{:error, reason, notif} = APNS.push(n)

# multiple pushes, one token each
%APNS.NotificationResponse{} = APNS.push([n, n])
```

**FCM**
```elixir
# one push, multiple tokens
n = FCM.Notification.new(["regid_1", "regid_2"], %{}, %{})
{:ok, %FCM.NotificationResponse{}} = FCM.push(n)

# multiple pushes, multiple tokens
n = FCM.Notification.new(["regid_1", "regid_2"], %{}, %{})
[ok: %FCM.NotificationResponse{}, ok: %FCM.NotificationResponse{}] = FCM.push([n, n])
```

This gets even more confusing with `:on_response` callbacks as FCM can expect either `%FCM.NotificationResponse{}` or `{:error, reason}` as its callback argument and APNS gets `{:ok, notif}` or `{:error, reason, notif}` for every single notification. Perhaps these should be reworked to provide a `NotificationResponse` for every callback, though this feels like overkill for APNS.

ADM's response is somewhat of a hybrid between APNS and FCM as it only supports one token per request but has FCM-like json responses. In that sense, the behavior should mimic APNS, which currently is to return a `NotificationResponse` only when a list of notifications is pushed synchronously.

**Comment by hpopp** [comment]
I would say for now, update it to better match APNS until I can think of a more unified solution. Suggestions are totally welcome if you have some ideas.

**Comment by talklittle** [comment]
Thanks for the explanation, I definitely missed the point of the NotificationResponse. I was only looking at FCM and did not realize APNS had 2 different response formats.

I think it makes sense to return NotificationResponse for all `:ok` results, including APNS, even if it feels like overkill. The consistency would be worth it IMO.

I'd say `{:error, reason}` can remain as-is, not sure if you were suggesting NotificationResponse for errors too.

**Comment by talklittle** [comment]
@hpopp I've added another commit with ADM synchronous push, mimicking APNS.

Unfortunately I am struggling to find a way to return 2 different types of responses for ADM to mimic APNS, since the NotificationResponse format is so similar to FCM. I think it would result in two largely different code paths, both within Pigeon and in the end-user application, for little-to-no benefit. So I hope you are okay merging as-is for now, and we can revisit as necessary in the future?

**Comment by hpopp** [comment]
Merging for now, but I'm still going to resolve the API before release. One of pigeon's original goals was to be *dead simple* to use, and I still feel like all of the current solutions thus far aren't complete.

**Comment by talklittle** [comment]
@hpopp Thanks. One simple alternative would be to keep NotificationResponse internal to Pigeon, and simply go back to using the `:on_response` callback from Pigeon 0.x. Just call the callback once per regID and per notification. That way end-users don't have to have as much boilerplate to traverse all the lists and maps of NotificationResponse.

And for synchronous calls, perhaps return a list of `[{:ok, notif}, {:ok, notif2}, {:error, reason, notif3}, ...]`?

One thing that I've found a bit more painful to deal with, as an end-user of Pigeon 1.x, is the `NotificationResponse.error` map, just because it's cumbersome to enumerate list values within a map, rather than a single flat enumerable list.

**Comment by hpopp** [comment]
Theres two main things we can't avoid:

1. Synchronous pushes have to chunk responses, or else you don't know what happened to each of them.
2. An `FCM.Notification` can be either thought of as one device or many, so when you push, sending to one or multiple devices is conceptually the same.

If we want to properly standardize the API, all three push services should be as conceptually close as possible.

This would mean that:
- Pushing a list of notifications asynchronously means that you would expect the callback to get called once for the list, just like synchronous. If you wanted it to be called once per notification, you would iterate over the list and push individually.

- APNS and ADM need to respect tokens/regIds the same as FCM. This is something I don't think is possible, or at least clean, to implement. The difference is that FCM can have multiple failures/successes in a single notification, while APNS and ADM only either failed or succeeded per notification. This is the part I'll have to think more on.

Also somewhat related, I'm thinking that the connection timeouts should return another error entirely, sort of like HTTPoison responses.

**Comment by hpopp** [comment]
> And for synchronous calls, perhaps return a list of [{:ok, notif}, {:ok, notif2}, {:error, reason, notif3}, ...]?

Heh, I guess I totally misread this and now my post seems kind of dumb. Let me look up the conventions in the standard library and see how commonly it's used. I personally dislike keyword lists with duplicate keys but it might make a lot of sense here.

**Comment by talklittle** [comment]
Maybe a bit of inspiration from Ecto.Repo (insert vs. insert_all, update vs. update_all) https://hexdocs.pm/ecto/Ecto.Repo.html

A single target returns `{:ok, schema}` or `{:error, changeset}`

Multiple targets return `{number_affected, [rows_affected]}`

And if you do away with `number_affected` then you end up with the simple list of tuples. `[{:ok, n1}, {:update, n2, new_reg_id}, {:error, reason, n3}]` Or a list of simpler/flatter NotificationResponse structs, though tuples feel simplest to me.

>  Also considering storing an `:error` key on the notification itself. This is how ruby's houston gem does it.

That is reasonable since I think Ecto also does this in the `{:error, changeset}` adding errors into the `changeset.errors` keyword list. Changeset is pretty analogous to notification.

**Comment by hpopp** [comment]
I really like the changeset analogy. I'm going to keep thinking because I'm still not sold on all of Ecto's API.

**Comment by hpopp** [comment]
I think I've decided on the best course of action for APNS, and possibly FCM/ADM as well. Every notification will have a `:response` key with the atom error (or `:success`, if successful). `APNS.push/2` will return a list of notifications with the updated key. For those making synchronous calls, this should play really nice with pipe chains.

```elixir
["token1", "token2"]
|> Enum.map(& APNS.Notification.new("msg", &1, "topic"))
|> APNS.push
|> Enum.each(& process_response(&1))

def process_response(%Notification{response: :success}), do: :ok
def process_response(%Notification{response: :bad_device_token}), do: # remove token
...
```

**Comment by talklittle** [comment]
That certainly looks elegant! 👍 for playing well with pipes.

I assume for FCM/ADM you wouldn't want to split the original `Notification` into separate `Notification`s per regID, since that's somewhat unintuitive. In that case maybe `response` value could be a list: `[{regId1, :success}, {regId2, :bad_device_token}, {regId3, :new_registration_id, newRegId3}, ...]`

**Comment by hpopp** [comment]
Yes, thats perfect, though I would probably make atoms come first so you could do things like
```elixir
Keyword.get_values(notification.response, :remove)
["regid_1", regid_2", ...]
```

I'm not sure if I'm missing something, but ADM notifications should be able to get returned just like APNS. I can make the appropriate changes.

**Comment by talklittle** [comment]
Keyword lists require 2-tuples. How will we handle `:update`? Nested tuple? `{:update, {oldRegId, newRegId}}`?

**Comment by hpopp** [comment]
That's what I was thinking yeah

**Pull request merged**
