### PR TITLE
Macro.underscore - no match of right hand side value: nil

### PR DESCRIPTION
**Pull request by jowi-dev**
Fix for #265

Adds an "unknown" response if the response error is nil

### CODE REVIEW

**Comment by jowi-dev** [comment]
I don't know who can take a peak at this, but this error is blowing up sentry logs for orgs who use Pigeon

**Comment by jowi-dev** [comment]
@hpopp apologies for the ping but this is a very very noisy error in production - any chance we can get this merged?

**Comment by hpopp** [comment]
Thanks for the heads up and fix. There's a deeper issue here though. Have you not upgraded to the new FCM? Legacy was officially decommissioned a few weeks ago, and they've been gradually turning things off since then.

https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by jowi-dev** [comment]
We are upgraded in the console, but I don't see anywhere that we can use the pigeon package in the way those migration guides are indicating. We are currently on the listed latest release at hex.pm of 1.6.3. I see the release candidates seem to have the new calling convention - are they stable enough to move forward with in production?

**Comment by hpopp** [comment]
I've been running RC2 in production for a while now, as are many others. The package is stable with two exceptions before the 2.0.0 official release:

1. Pigeon.LegacyFCM will be going away completely (because it's no longer available)
2. The FCM dispatcher setup will be changing a bit (see #235)

Regarding item 2, the core of FCM won't be changing (e.g. notification struct, how you send notifications). Only the configuration of the adapter to authorize with FCM APIs. It should be relatively easy to make the necessary changes once published.

Honestly I should've made these changes ahead of the shutoff date. To unblock yourself, I'd version lock at RC2 and I'll prioritize getting these updates finalized (with appropriate CHANGELOG docs).

**Comment by Sinc63** [comment]
Henry, is there any chance that you could merge this today? I have an extension on getting my pushes converted to V1 (until September 20th) but I discovered today that the old version of my app was using an old project number not covered by the extension, and now I'm getting the above error against the old project number. I can fork the branch again but it would be simpler if you could merge immediately. (yeah, yeah, not going to happen, just asking.)

I'm glad to see that you plan to merge 235. With that in my fork I have succeeded in getting pushes to work (mostly related to correcting the project number) and it would be good to be running a released version instead of the release candidate. Something released in the next week would be great.

**Comment by hpopp** [comment]
Sure, merging, I'll clean up CI on master.

**Pull request merged**
