### PR TITLE
Document Runtime Workers

### PR DESCRIPTION
**Pull request by halostatue**
- Allow multiple workers to be returned by a single function (nil workers will
  be filtered out).
- Expose Pigon.FCM.Config documentation.

### CODE REVIEW

**Comment by halostatue** [comment]
This is something of a WIP and I haven’t tested it in my own code yet.

**Comment by halostatue** [comment]
The build is failing because Travis has removed encrypted environment variables.

**Comment by hpopp** [comment]
No worries on the build failing, things pass fine locally. I went ahead and make the README the default page for hexdocs.

Awesome work on this! It's a solid writeup. I'm beginning to wonder if letting pigeon manage the workers is ultimately the best approach. It seems like in your example use case, it would actually make more sense to run the workers in the application's supervision tree.

Here's all of the current ways to run a worker:
- Statically configured in the mix config
- Runtime configured, supervised by pigeon via the `:workers` list
- Runtime configured, supervised by your application via worker specs
- Runtime configured, outside of a supervision tree via `Pigeon.start_connection/1`

Perhaps this is worth opening an issue for discussion. Given how configuration has evolved in elixir 1.9, it might make more sense to drop the first two and require the user to supervise their own workers in pigeon `2.0`. Curious to hear you thoughts on this.

**Comment by halostatue** [comment]
It could be. I’d probably want to make it so that I could start a Pigeon supervisor the same way that I do a Cloak `Vault` or an Ecto `Repo`, and it would supervisor the workers provided by configuration.

For my case, I absolutely have to have run-time configuration as I can’t even consider putting the secret keys directly in Heroku configuration or the repo, as the case may be. This particular setup makes things work a little more like [rpush](https://www.github.com/rpush/rpush), although with manual handling of the database application definitions (which I think is the _right_ choice, BTW).

I think that, for demo purposes, the static configuration is cool…but it’s no way to deploy an application in production. That should be removed, at a minimum. The other suggestion is to follow the recommendations for Ecto and use an `init/2` callback.

I’m pretty happy with what I’ve come up with, but if Pigeon didn’t have its own application, my job would have been much easier (but everyone else’s job would be harder).

**Comment by halostatue** [comment]
I’m wondering if this can be merged and released in the interim as it is backwards compatible with the current approach and potentially provides a recommended path for the breaking changes in 2.0 (removing the application and making it a supervised tree that has to be started in one’s own application).

**Comment by hpopp** [comment]
Published!

**Pull request merged**
