### PR TITLE
GCM renamed to FCM

### PR DESCRIPTION
**Pull request by hpopp**
Changes:
- FCM worker connection config made similar to APNS
- `FCM.Worker` uses Http2.Client interface (instead of Kadabra hardcoded)
- Workers and things moved into their own `apns/fcm/adm` subdirectories

To fix:
- Chatterbox client not receiving END_STREAMs for FCM pushes

Other Todos:
- ADM needs to be reworked for custom worker configs (similar to APNS/FCM)
- Update documentation to reflect all of these changes

### CODE REVIEW

**Comment by hpopp** [comment]
@cstar 
Everything looks almost good to go. Anything `GCM` has been renamed to `FCM`. I'm going to update the README to mark `GCM` officially supported on `v0.13` and older, with everything `v1.0+` as FCM-only. 

New config style looks like
```
config, :pigeon, :fcm,
  fcm_default: %{
    key: "api_key"
  }
```

The `:fcm_key` option has been renamed to `:key`. Ideally this option would only be used if you wanted to maintain one default connection and override. Custom workers can now be pushed with the `:to` option, similar to APNS.

Did chatterbox ever work for you with the updated FCM worker? I changed the hardcoded kadabra calls to use the `Http2.Client` interface, but chatterbox doesn't seem to be getting any `END_STREAM`s.

@talklittle 
ADM workers need to be updated to match the APNS/FCM config style. I can do this myself unless you want to take a crack at it. It should be almost identical to the APNS config setup. (Maybe its worth abstracting it?)

**Comment by talklittle** [comment]
@hpopp Sure I can take a look at the ADM worker config.

**Comment by talklittle** [comment]
@hpopp Updated the ADM config style and tested to make sure the ADM default worker is started and accepting pushes.

This commit https://github.com/talklittle/pigeon/commit/b74acf9656d76224605f1c95dc3bc6cd957d6482

On this branch https://github.com/talklittle/pigeon/tree/adm-config

If all looks fine then probably easiest to `git cherry-pick` that commit into this PR. Or let me know if you want me to submit a separate PR after you merge this one.

**Comment by hpopp** [comment]
Everything looks good. I'm fine waiting for a separate PR-- I want you to get credit for it.

**Comment by hpopp** [comment]
Going to remove the Chatterbox client adapter for `1.0` until further notice. Doesn't play nice with FCM servers. Push streams get immediately reset with a `PROTOCOL_ERROR`.

Making a note of received packets for connection setup and push
```
<<0,0,18,4,0,0,0,0,0,0,3,0,0,0,100,0,4,0,16,0,0,0,6,0,0,64,0,0,0,4,8,0,0,0,0,0,0,15,0,1>>
0x4 - Settings
[{"SETTINGS_MAX_CONCURRENT_STREAMS", 100},
 {"SETTINGS_INITIAL_WINDOW_SIZE", 1048576},        
 {"SETTINGS_MAX_HEADER_LIST_SIZE", 16384}]
0x8 - Window Update, stream 0, payload <<0, 15, 0, 1>>

<<0,0,0,4,1,0,0,0,0,0,0,4,3,0,0,0,0,1,0,0,0,1>>
0x4 - Settings ACK
0x3 - RST_STREAM, PROTOCOL ERROR

<<0,0,4,3,0,0,0,0,1,0,0,0,1>>
0x3 - RST_STREAM, PROTOCOL ERROR
```

**Comment by hpopp** [comment]
@talklittle Everything's now merged. Open up a PR and I'll add your changes.

**Pull request merged**
