### PR TITLE
Support for token based APNS authentication

### PR DESCRIPTION
**Pull request by Lankester**
JWT handling is via Joken, an additional dependency.

As the token is valid for an hour I have added an Agent to store the generated token, this prevents the token from being regenerated for each notification. The token will refresh once it's just under one hour old.

### CODE REVIEW

**Comment by hpopp** [comment]
Thanks for this!

Couple things that need to be changed before merge:
1. `APNS.Token` needs to support multiple tokens and expirations.
2. All JWT functionality should be moved into a `%Pigeon.APNS.JWTConfig{}` struct that implements the `Configurable` protocol. There will be a fair amount of overlap with `APNS.Config`, so much of it could be refactored into a shared module.

Configs defined in the `config.exs` are a bit open ended, so it could either be a normal or JWT config. I would likely raise an exception if both `:cert` and `:key_identifier` are defined, else parse the respective config struct.

**Comment by Lankester** [comment]
Thanks for the feedback.

1. I can't believe I missed that! I've updated `APNS.Token` to store and retrieve tokens against the `name` key of the config.
2. Refactored as suggested. `APNS.CertConfig` delegates to `APNS.Shared`, as does `APNS.JWTConfig` but with the JWT authentication handling.

There is also a `Pigeon.ConfigError` exception that should raise when `:jwt_key` and `:cert` are both set. Also when neither are present.

Happy to make further adjustments.

**Comment by hpopp** [comment]
* `APNS.CertConfig` was moved back to `APNS.Config` to maintain backwards compatibility.
* Static configs now check for `:key_identifier`, as I removed several `jwt_` prefixes from the `JWTConfig` attributes and it conflicted with the existing `APNS.Config` `:key`.

I still need to add some tests for JWT keyfiles, and make sure the docs are good to go with the new changes.

Also TODO:
* `APNS.Token` needs to key based on a combination of team ID and key ID, as APNS workers started dynamically do not have names.

**Comment by Lankester** [comment]
`APNS.Token` now keyed on a combination of `:key_identifier` and `:team_id`.

**Pull request merged**
