### PR TITLE
Add priority option for GCM

### PR DESCRIPTION
**Pull request by mkaszubowski**
https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message

I think there is no option to set priority at the moment and it's quite an important feature. Please let me know what you think. If you're ok with the implementation, I'll add some information about it to the docs.

### CODE REVIEW

**Comment by mkaszubowski** [comment]
@hpopp I'm sure you're busy, so I'm bumping this in case you've missed it :)

**Comment by hpopp** [comment]
Haven't forgotten, just forgot to reply! I do intend to include this in `v1.0` but I'd like to get the other GCM changes finalized before we merge this in.

**Comment by mkaszubowski** [comment]
Sure, sounds great! You can ping me when the other GCM PR is merged, I can then fix/update this one :)

**Comment by hpopp** [comment]
FCM functionality pushed to master. Still have some things left to tweak before a hex release, but if you'd like to pull changes and fix up this PR I'll merge it in.

**Comment by mkaszubowski** [comment]
@hpopp  Sorry it took so long, but I finally found the time to update this. Please tell me what you think :)

**Comment by mkaszubowski** [comment]
Also, let me know if you would like me to squash all the commits into one

**Comment by hpopp** [comment]
Looks good! I was able to squash in the merge.

**Pull request merged**
