### PR TITLE
v1.1.0

### PR DESCRIPTION
**Pull request by hpopp**
- [x] Bump kadabra to `v0.3.0` (Requires Elixir 1.4/OTP 19.2)
- [x] Dynamic environment configs (#74)
- [x] Generic HTTP2 worker interface
- [x] HTTP2 custom client adapter guide (#87)
- [x] Enable/disable push logs (#48)
- [x] Synchronous `ADM.push/2`
- [x] `%ADM.NotificationResponse{}`

### CODE REVIEW

**Comment by hpopp** [comment]
@talklittle I noticed `ADM.push/2` isn't synchronous by default, but will need something similar to `FCM.NotificationResponse` if we want to send a list of notifications.

Are the json error responses similar to FCM? I'm thinking it's going to be somewhat of a hybrid between the APNS and FCM responses. Kind of like:

```elixir
%Pigeon.ADM.NotificationResponse{
  ok: [notif_1, notif_2],
  update: [notif_3],
  retry: [notif_4],
  error: %{
    invalid_json: [notif_5]
  }
}
```

**Comment by talklittle** [comment]
@hpopp That sounds about right. I'll work on ADM NotificationResponse.

**Comment by hpopp** [comment]
@talklittle Everything is almost ready except for final decisions on the FCM api.

If a request-level error happens, `:response` needs to be updated accordingly, but it really should still be enumerable. There's a few options here:

1. Map the request-wide error to each regid. Something like `:timeout` then becomes `[{:timeout, "regid1"}, {:timeout, "regid2"}, ...]`. This makes it less obvious if the whole notification failed.

2. Add several keys for the remove/retry/etc and list the corresponding regids, while `:response` itself indicates either `:success` or one of the request-wide errors. Notifications would look like

```elixir
%Notification{
  registration_ids: [...],
  response: :success,
  success: ["regid1"],
  remove: ["regid2, "regid3"],
  update: [{"regid4", "regid4_2"}],
  retry: ["regid5"]
  error: %{
    other_error: ["regid6"]
  }
}

# or

%Notification{
  registration_ids: [...],
  response: :timeout,
  success: [],
  remove: [],
  update: [],
  retry: [],
  error: %{}
}
```

3. Add a `:success?` key that if true, `:response` is a list of regid responses, else an atom indicating the error.

```elixir
%Notification{
  registration_ids: [...],
  success?: true,
  response: [success: "regid1", invalid_registration: "regid2", ...]
}

# or

%Notification{
  registration_ids: [...],
  success?: false,
  response: :timeout
}
```

I'm personally inclined to go with `#2`, though I'm open to ideas here.

**Comment by hpopp** [comment]
Also an option, a hybrid of `#2` and `#3`

```elixir
%Notification{
  registration_ids: [...],
  response: :success,
  registration_id_responses: [success: "regid1", invalid_registration: "regid2", ...]
}

# or

%Notification{
  registration_ids: [...],
  response: :timeout,
  registration_id_responses: []
}
```

**Comment by talklittle** [comment]
Hmm, sorry but I still am of the opinion that something close to `#1` would be easiest for the end-user application. It's easier to enumerate over a flat list, with function heads to pattern match success/update/remove/etc. The map feels less idiomatic to Elixir, since it requires an extra flattening step to get something enumerable/pattern-matchable.

How about when handling the request-wide error, instead of mapping that error to each regID separately, just return `{:error, reason}` instead of the successful `{:ok, notif}` (and add a `push!/2` method to raise in case of request-wide errors). I think this approach closely matches the APIs of the most popular Elixir libraries that I am familiar with. Also APNS was kind of doing this already, IIRC you mentioned in a prior comment.

**Comment by hpopp** [comment]
My only issue, `#1` breaks the concept of the request itself. If a 400 or 500-level error happened, you would expect to retry the whole push again, not on a per-regid basis.

Instead of tagged tuples, APNS and ADM were reworked to use a `:response` key, and it achieved extremely clean enumerability. In the case of FCM, individual regid responses are already nested inside the struct, so you'll have to do flattening at some point.

The hybrid 2/3 approach still allows for enumerability, just with the intermediary catch-all in case the whole request failed.

```elixir
def handle_response(%FCM.Notification{response: :success, registration_id_response: responses}) do
  Enum.map(responses, & handle_regid(&1))
end
def handle_response(_else) do
  # some sort of error
end

def handle_regid({:update, {old, new}), do: #update
def handle_regid({:invalid_registration, regid), do: #remove
def handle_regid({:not_registered, regid}), do: #remove
def handle_regid({:unavailable, regid), do: #retry
...

FCM.push(notif, on_response: &handle_response/1)
```

**Comment by talklittle** [comment]
@hpopp Thanks a lot for the illustration! That's a lot cleaner than what I had been picturing in my head. It resembles the HTTPoison API. I like it.

Minor nitpick: maybe rename `:response` to `:status` and `:registration_id_response` to `:response`?

**Comment by hpopp** [comment]
I like those keys a lot better 👍

**Comment by talklittle** [comment]
I'll be happy to give it a shot this week if you publish a `1.1.0-rc.0`

**Comment by hpopp** [comment]
Published, I'll be testing as well on some of my production apps.

**Comment by talklittle** [comment]
`1.1.0-rc.1` has been working well for the past 24 hours, no issues so far.

**Comment by talklittle** [comment]
Unfortunately I think something is wrong with the FCM support (maybe Kadabra?). Maybe tied to the intermittent `GOAWAY, session_timed_out` I had been seeing but ignoring. After about 3 days uptime, the notifications are no longer being sent. No error message when trying to push, but also no longer seeing the `session_timed_out` errors at all, which leads me to believe there is no "session" currently connected.

**Comment by hpopp** [comment]
FCM drops its connection after a couple minutes, and if you reconnect, it'll halve that time each reconnect. By default now it lets the connection die and restarts it on the next push batch.

Logging can be re-enabled with
```elixir
config :pigeon, debug_log: true
```

Perhaps check if anything is getting sent at all?

**Comment by talklittle** [comment]
Will enable logging and report back in 3-4 days.

**Comment by talklittle** [comment]
The problem hasn't come back in the past 4 days. I guess it was a fluke? (Although it happened 2 times, I think...) If nobody else has seen FCM problems with 1.1.0-rc.1 then I suppose it's probably safe enough to release.

**Comment by hpopp** [comment]
Do you use pigeon for APNS? I've gotten the occasional error where servers close with a `GOAWAY {reason: Shutdown}` and it throws into an infinite reconnect loop. I'm considering disabling APNS reconnect by default, or maybe removing it entirely.

**Comment by talklittle** [comment]
No APNS, only FCM and ADM here. FCM has been working fine the past week, auto reconnecting after timeouts. ADM I've caught 1 timeout (crash because I didn't handle it in my application) and the supervision tree seemed to recover properly afterward.

**Pull request merged**
