### PR TITLE
async: spawn/1 instead of Task.async/1

### LINKED ISSUE #62: Issue in GCM Pusher: failing to call Task.await
I have a GenServer running that sends out push notifications using pigeon. I have recently updated to 0.10.3 and I started seeing the following messages every time I sent a GCM push notification:

```
22:51:05.504 [warn] Reverb.Backend.Pusher Reverb.Backend.Pusher received unexpected message in handle_info/2: {#Reference<0.0.3.2852>, [nil]}

22:51:05.504 [warn] Reverb.Backend.Pusher Reverb.Backend.Pusher received unexpected message in handle_info/2: {:DOWN, #Reference<0.0.3.2852>, :process, #PID<0.2565.0>, :normal}
```

After tracking this down, it appears that on line [59 of gcm.ex](https://github.com/codedge-llc/pigeon/blob/master/lib/pigeon/gcm.ex#L59), you are calling `Task.async` but never calling `Task.await`. 

When the Task finishes, this causes the DOWN message to be sent to the parent, which is my GenServer. According to the [elixir documentation](https://hexdocs.pm/elixir/Task.html#async/3), you should always be calling Task.await for every Task.async

### PR DESCRIPTION
**Pull request by talklittle**
since Task.async/1 must have Task.await/2

fixes #62

### CODE REVIEW

**Comment by hpopp** [comment]
Thanks for this, I've been putting out other fires this morning with completely unrelated stuff

**Comment by hpopp** [comment]
I having trouble getting two of the GCM unit tests to pass:

```
1) test successfully sends a valid push with callback (Pigeon.GCMTest)
2) test returns an error on pushing with a bad registration_id (Pigeon.GCMTest)
```

Do these work for you locally?

**Comment by hpopp** [comment]
Got them to pass by changing `spawn` to `Task.start_link/1`, which is recommended for tasks that aren't expected to return a result.

**Comment by talklittle** [comment]
@hpopp Sorry, I ran tests of a subproject, I broke these Pigeon unit tests. The logic seems to work e.g. if I replace the unit test code with:

    Pigeon.GCM.push(n, fn(x) -> IO.inspect("hey sup!!!") end)

But I think there might be something wrong with the `send self(), x` where `self()` might not be getting the message back to the original process, since it's no longer linked the way `Task.async/1` links the 2 processes together. I will try to fix the unit tests.

**Comment by talklittle** [comment]
@hpopp Oops, okay thanks for finding that fix. Sorry again for breaking the tests.

**Comment by mkaszubowski** [comment]
@hpopp Shouldn't you use `Task.Supervisor` here (https://hexdocs.pm/elixir/Task.Supervisor.html#async_nolink/2)? `Task.start_link/1` creates a link between the processes which will cause the worker to crash if the task crashes. By using the `Task.Supervisor.async_nolink` or `Task.Supervisor.start_child` you could isolate the processes.

**Comment by talklittle** [comment]
@hpopp FWIW I believe the change you made to the unit test

    pid = self()

was the real fix, matching up with my prior comment. I changed the GCM code back to `spawn/1` locally and it seems to work. I don't think it's necessary to link the 2 processes together.

**Comment by hpopp** [comment]
I couldn't get `spawn/1` to work locally with the test change. Ran my suite again just now and it works great ¯\_(ツ)_/¯

Reverting back the changes.

**Pull request merged**
